name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.*
          check-latest: true
      - name: Install libczmq-dev
        run: sudo apt-get install -y libczmq-dev
      - name: Build
        run: go build -o scaled-scheduler-go -ldflags="-s -w"
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: scaled-scheduler-go-linux
          path: scaled-scheduler-go
  release:
    needs: [ build-linux ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: scaled-scheduler-go-linux
      - name: Tar Gzip Linux release
        run: tar -czvf scaled_scheduler_go_${{github.ref_name}}_linux_amd64.tar.gz scaled-scheduler-go README.md LICENSE
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            scaled_scheduler_go_${{github.ref_name}}_linux_amd64.tar.gz
